test/pspm_ecg2hb_amri_test.m

- With 4d0cf4d pspm_ecg2hb_amri only returns heartbeat seconds and not a logic vector of the same length as the input. Hence, this test is removed.

Remove output channel length test from ecg2hb_amri test

---

src/pspm_version.m

Fixes #39 .
- Fixed the problem using `webread` function and `try ... catch ... end` method.
- Works with `-nojvm -nodesktop -nobatch` .
- In case of error with url reading, the warning is still sent.

Issue #39 pspm_version.m solution for the bug

---

.gitignore

Update gitignore so that it ignores
- Jekyll related files
- lyx swap files (`.lyx~`)

Add jekyll and lyx ignore rules to gitignore

---

src/pspm_hb2hp.m

Fixes #48 .
- `try options.channel_actions catch ... ` is an always true action, that means it will always catch, that's why I changed it to `if` statements.

Issue48 hb2hp bug

---

src/Import/viewpoint/import_viewpoint.m

Fixes #53 .
- Add extra check to "new session marker" detection: a marker should only contain `+,=` characters.

Check if a marker only contains one of +,= for splitting

---

src/Import/viewpoint/import_viewpoint.m

- Although in #53 we fixed the session begin index definition, we forgot a case: if a marker doesn't contain a `+` marker, it cannot be counted as a session begin marker. This pull request fixes this issue

Make sure there is a + marker in sess begin markers in import_viewpoint

---

test/pspm_glm_test.m

In `pspm_glm` tests, there is a case where the input signal was set to a complete `NaN` signal. This testcase is currently disabled.

Remove all NaN signal test from pspm_glm tests

---

src/pspm_get_events.m
test/pspm_get_events_test.m

- In #15 we fixed the issue regarding missing the first marker in a file. However, our implementation misses a few cases that were tested in `pspm_get_events_test`. This pull request handles these issues. The main idea of the proposed changes are as below:
* We missed two usecases: the input signal may be shifted by a baseline and the pulses might also be triangular. To handle both of these cases with the new code, there is a new signal normalization portion added.
* Since we use a normalized signal for detection, the original signal is stored in an extra variable in order to return correct marker values later in the code.

Extend get_events bugfix according to the previously implemented tests

---

src/pspm_version.m

Fixes #40 .
- I've just changed the url in `pspm_version.m` file and it works due to the fact that `https://bachlab.github.io/PsPM/`.

Changed the url in pspm_version.m

---

src/Import/eyelink/import_eyelink.m
src/pspm_get_events.m
src/pspm_get_eyelink.m

Fixes #67 .
Changes proposed in this pull request (per file):
1. `import_eyelink.m` : 
- implement a condition that does not allow us to import markers which are outside the session end time (i.e. the last timestamp before the marker `END`)
2. `pspm_get_events.m` :
- added a new `import.flank` parameter called `'all'` which imports all markers and data related to them.
- `pspm_get_eyelink` function calls `pspm_get_events` in order to transform the original continuous markers data to an vector of "events", but when it encounter data such as the following one it will consider consecutive markers as one continuous one and thus with the option `ascending` it will catch the timestamp only of the first one.
```
------ Raw Eyelink data -------    ------ Data that pspm_get_events receives ------- …
```

Fix/issue67 : New procedure for catching markers in an Eyelink file

---

doc/PsPM_Manual.lyx

Fixes #80  .
- Added a warning in the tutorial to inform users that the Signal Processing Toolbox is needed for the tutorial. (Dominik's request)
I don't know who is responsible for publishing tutorial data, that's why I haven't done.

Added a warning in the tutorial about the toolbox.

---

doc/PsPM_Manual.lyx

Fixes #80  .
- Change the file naming in DCM data as mentioned in #80. This new data is uploaded both to old sourceforge website and our new data storage website on github: https://github.com/bachlab/PsPM-tutorial-datasets/releases
- Update the links to tutorial datasets in the manual to PsPM website

Change GLM and DCM tutorial data links

---

src/pspm_pupil_correct_eyelink.m

- Use the last gaze channel in `pspm_pupil_correct_eyelink` when there are multiple gaze x (similarly y) channels in the file.
This is a reasonable default (which is also the case in GLM) since preprocessing functions either append the new channel to the pspm file or replace (in which case this option is irrelevant anyways).

Use the last gaze chan in pupil_correct_eyelink

---

src/pspm_extract_segments.m
test/pspm_extract_segments_test.m
test/pspm_glm_test.m

Fixes #107 .
- Return `NaN` percentages, not ratios from `pspm_extract_segments`

Mult NaN ratio with 100 in extract_segments

---

src/pspm_butter.m

Fixes NaN.
- access filt struct after loading.
Guillame Flandin from SPM pointed out access the filt from the struct in a chained fashion from the load would fail in older versions of matlab

fix(struct-load): access after load

---

src/pspm_rev_dcm.m

Fixes #124  .
- Scale xticks by the sample rate from the dcm input data

fix(dcm-xticks): scale xtick label by sample rate

---

src/pspm_split_sessions.m

Fixes an issue spotted by Jelena.
Issue description:
When trying to split session per blocks using `pspm_split_sessions` in data where marker distances are not constant (random ITI), you can end up with session which contains more markers than needed. 
Example: you have 40 markers in data and 4 blocks, you want to split uniformly, but due to random marker distances (not going much in details) the session 3 is found to have 11 markers instead of 10 such that after processing and recombining the data you will have 41 markers instead of 40.
- In this pull request, I implemented an option which I called `randomITI` and which can take the values 1 or 0 (default: 0)
- What it does is to evaluate the mean marker distance not per session but on the all the …

Add an option to take into account random ITIs

---

src/pspm_get_events.m
test/pspm_get_marker_test.m

Fixes #115  .
- correct index offset when dealing with the descending flank for continuous markers

fix(descending marker events): update index for descending events

---

src/Import/viewpoint/import_viewpoint.m
test/import_viewpoint_test.m

Fixes a bug that I've discovered while importing a viewpoint file. Here is a test file (anonymized): [test_data.txt](https://github.com/bachlab/PsPM/files/4959048/test_data.txt)
*Bug description:*
For importing a viewpoint file in PsPM, `import_viewpoint` function uses `textscan` Matlab function to read formatted data from the text file. The format is determined by a `formatSpecs` character array which is created by `get_columns_to_read` function (cf. `import_viewpoint.m` file), e.g. `%f\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%s` (num. of col depend on the file). But as one can see it already contains the delimiter and thus it shouldn't be specified in options of the `textscan` function. Moreover when specifying it the `textscan` stops at the first marker because `formatSpecs` do not …

import_viewpoint doesn't import the right number of datapoints

---

src/pspm_display.m

Fixes an issue reported by @dominikbach .
In the current implementation, `pspm_display` crashes when someone first plots data with many wave/event channels and then tries to load data with less wave/events channels.
- execute `pspm_display('any_pspm_data_file.mat')`
- lets say it has 7 wave channels
- select and plot channel 6 for instance
- now click on the button "load" in the top left corner of the window
- select a file which has less than 6 wave channels
- click "Done.", you'll then see a warning in the Command window and on top of that the wave list box will disappear !
(same procedure with event channels)
What `pspm_display` currently does is just to replace the list in the `wave_listbox`/`event_listbox` instances but not the value of the list box, so when it finishes the loading …

pspm_display crashes when loading data

---

src/pspm_dcm.m
src/pspm_dcm_inv.m

Improvement suggested by Karita.
Previously `pspm_dcm` was not catching all the warnings which didn't lead to an end of file (i.e. not followed by a "return;"), typically the warning emitted by the function `get_data_after_trial_filling_with_nans_when_necessary` (btw we have to find a new shorter and more explicit name for it) was forgotten. 
This is especially anoying when DCM is used for many subjects at once, because the user has to scroll the command window history in order to find which subject had a warning.
- A new (easier ?) implementation for saving warnings which do not lead to a "return;".
- Add a forgotten "return;" in `pspm_dcm_inv`

Modify the way warnings are stored in pspm_dcm

---

src/pspm_split_sessions.m

Fixes a bug I noticed during my own data processing.
This was a copy-paste-multiplied typo ('maker' instead of 'marker'), as a result of which pspm_split_sessions would not copy existing "markerinfo" into the newly created files.

Fix pspm_split_sessions

---

src/pspm_split_sessions.m
src/pspm_trim.m
test/pspm_split_sessions_test.m

Fixes #250, #251, #254 
- fix bug with overwrite
- enable full use of pspm_trim, thus slashing down code volume in pspm_split_sessions
- this removes a remaining bug (typo: makerinfo instead of markerinfo)

fix bugs in split_sessions

---

src/pspm_load_data.m

Minor change to pspm_load_data: return index of the channels that are returned. Useful for functions that only accept channel numbers rather than channel types (e.g. pspm_extract_segments).

Add a new feature in return values of pspm_load_data (channel index)

---

src/pspm_dcm.m
src/pspm_dcm_inv.m

Fixes #280 
- sort missing epochs in pspm_dcm
- fix additional bug in the detection and processing of "short" missing epochs - at the moment these are not ignored if missing epochs are defined per missing epochs file, and they are incorrectly used when defined as NaN values

Sort missing epochs in pspm_dcm

---

src/pspm_init.m

Fixes #298 .
- Update the default value for SOA in `pspm_bf_spsrf_box`.
Now `pspm_init` is updated and has the default value as 3.5 for SOA.

Fix issue 298

---

.editorconfig

- Create .editorconfig
[.editorconfig](https://editorconfig.org) sorted the code style across a repository. There are currently some confusing code styles (CRLF/LF, Western Europe/UTF-8) which may disrupt code reviewing. This config file can sort and generalise the code style and avoid repetitive code style confusion.

Add the editorconfig file

---

src/pspm_glm.m

Fixes #338.
- Add a warning when input data was filtered out more than 10% due to missing epoch detection.
- Specify the reason of missing epochs in the warning after checking sampling rates.

Fix issue 338 - pspm_glm

---

src/pspm_data_editor.m
src/pspm_overwrite.m
test/pspm_scr_pp_test.m

Fixes #375.
- Update logic of overwrite
- This bug was caused by the missing inherited overwrite value from the options 
- Update the logic of displaying missing epochs, when loading data from command line windows
- This bug was caused by the missing updates of the epochs when they were loaded from the command line

Fix issue 375 - pspm_data_editor

---

src/pspm_split_sessions.m

this fixes a bug where pspm_split_sessions would return a faulty split epochs file when both split points where in the middle of epochs (i.e. numel(epoch_on) = numel(epoch_off) but the first offset is *before* the first onset).

fix edge case when splitting epoch files

---

src/pspm_extract_segments.m
src/pspm_options.m

- Update length value validation in `pspm_options` for `pspm_extract_segments`.
The value length is expected to be a negative value and should not be zero of positive. In line 485--495 at `pspm_extract_segments`, the checking code assumes the `.length` is always positive.

pspm_extract_segment length value checking

---

src/pspm_con2.m
src/pspm_data_editor.m
src/pspm_get_markerinfo.m
src/pspm_import.m
src/pspm_options.m
src/pspm_segment_mean.m

Fixes the overwrite issue that was proposed by users.
The behaviour of overwriting is controlled by two factors: (1) the default values set in `pspm_options`; (2) the checking in `pspm_overwrite`. However, some functions that call `pspm_overwrite` are not overwriting files properly, because the returned values from `pspm_overwrite` were not only the overwriting marker but also the status marker that is used as a general rule in PsPM. This pull request is therefore fixing the behaviour of `pspm_overwrite`.
The expected behaviour of `pspm_overwrite` is to always overwrite if no corresponding file exists in the path.
The return value of `pspm_overwrite` is called and used for determine whether to overwrite files. This is corrected for 
* `con2`: line 76---77
* `data_editor`: line 202---203
* …

Fix issue overwrite

---

src/pspm_cfg/pspm_cfg_sf.m
src/pspm_interp1.m
src/pspm_resp_pp.m

Users reported an issue when the input data contains NaNs. The issues is caused by the approach of calculating mean and interpolating at `pspm_resp_pp`, `pspm_prepdata`, `pspm_interp1`. The expected behaviour is listed as below:
1. In `pspm_interp1`, interpolation should be performed if the data contains at least two non-NaN values.
2. Data as the input of `pspm_prepdata` should be carefully checked to avoid being converted into NaNs due to other calculations, for example calculating the mean.
The pull request fixes #500.
- Update `pspm_interp1`
- Add data checking for `pspm_interp1`.
- Update `pspm_resp_pp`
- Avoid _NaN_ converting when performing mean-based filtering.

Fix issue 500 -- pspm_interp1

---

src/pspm_split_sessions.m

Fix a minor bug in `pspm_split_sessions`.
The bug is that the option `marker_chan_num` has not been used in `pspm_trim` (Line 208). The value of `marker_chan_num` is `markerchannel`, which is the input of the function itself.

Fix `pspm_split_sessions`

---

src/pspm_cfg/pspm_cfg_sf.m
src/pspm_sf.m

Issue #486: Users reported an issue when loading data and running SF analysis.
This pull request attempts to fix the issue #503 for `pspm_sf` and its relevant functions. Users have reported that `pspm_sf` will report errors when processing data whose `time_unit` is defined as `marker`. A series of issues are also discovered and marked during investigating this issue. The results are function-specifically listed below for discussing.
`pspm_sf` should be updated in line with the last update, i.e. `pspm_sf_dcm` should accept `model` and `options`.
`SF model` should allow `missing epochs` as an optional field. Now it looks like below.
In this window, `missing epochs` is an optional field to add. Users can add missing epochs if they need and ignore missing epochs as default if they do not need …

Fix issue 503 --- pspm_sf relevant functions

---

src/pspm_version.m

Fixes #514.
The issue appears as PsPM cannot be started when it is called offline. The reason of this issue is, at line 63 and 66 the script is terminated if it is offline, which will not assign values to the expected values `sts` and `version_of_pspm`.
Under the offline situation, the variables `sts` and `version_of_pspm` should be still assigned in `pspm_version`, before the script `pspm_version` is terminated.
At line 63 and 66, the `return` behaviour is removed, because the return values should be assigned at line 73--79.
The `new_v` is not assigned because version checking cannot be performed.
PsPM can be started when offline with the new code, after testing.

Fix issue 514

---

src/pspm_overwrite.m
test/pspm_find_valid_fixations_test.m
test/pspm_interpolate_test.m
test/pspm_load1_test.m
test/pspm_overwrite_test.m
test/pspm_pp_test.m
test/pspm_process_illuminance_test.m

This pull request is to update the logic of `pspm_overwrite`.
The logic of `pspm_overwrite` is now clearer based on the following aspects:
1. "Overwriting" should only happen when there has been a file with the same name of the file PsPM would like to write. Therefore, if there is no file with the same name, PsPM should always be allowed to write. This is now described at Line 83--85 in `pspm_overwrite`.
2. If PsPM is in develop mode, "overwriting" should always be allowed because the files that may be overwritten are artificial data. This is now set at line 79--82 in `pspm_overwrite`.

update overwrite logic

---

src/pspm.m

Fixes #555.
The main reason that leads to the issue mentioned by the user is caused by the incompatibility between app designer and older version MATLAB (2018) on Linux. This issue has been fixed in this pull request. Specifically, only newer versions of MATLAB (>2022) on Linux are now using app designer, and the earlier versions are now using GUIDE version.

Fix issue 555 -- pspm_init

---

src/pspm_split_sessions.m
test/pspm_split_sessions_test.m

Fixes #563 .
- avoids markers being dropped in secondary marker channels before first or after last marker of primary channel during pspm_split_sessions
- as a consequence, no trimming is done for the first and last session

adapt pspm_split_sessions

---

src/pspm_convert_hb2hp.m
src/pspm_quit.m
test/pspm_convert_hb2hp_test.m

Fixes #590 .
- pspm_convert_hb2hp
- Make `hb2hp` to select the last channel
- Change the logic of heart rate channel selection. Only the last channel should be selected, if there are multiple heart rate channels.
Let me test it with artificial data before making it available to review...

Fix issue 590 -- convert_hb2hp

---

src/pspm_glm.m

- fix a bug in pspm_glm that leads to markers being taken from the first marker channel, but markervalues from the last
- this is urgent and should be included in the upcoming hotfix

fix bug in selection of marker channel in pspm_glm

---

src/pspm_dcm.m

- fix a bug that could lead to a wrong sample rate being used if more than one SCR channel existed in the file, and they had different sample rate 
- specifically, this line of code erroneously used the sample rate of the **first** retrieved SCR channel, but the data from the **last** should be used
- this is urgent and should be included in the upcoming hotfix

fix bug in DCM

---

src/pspm_import.m

Fixes a bug whereby path separators are interpreted as escape characters by `fprintf` in `pspm_import`.

fix import output

---

src/pspm_data_editor.m

Fixes a user-reported bug in overwriting existing files in `pspm_data_editor`.

fix overwriting in data editor

---

src/pspm_cfg/pspm_cfg_split_sessions.m

Fixes #606.
- Bug fix for `split_sessions`'s GUI. This issue is caused by incorrect default value for `missing` if it is unspecified.

Fix 606 -- GUI issue for split_sessions

---

src/pspm_convert_ecg2hb.m
src/pspm_dcm_inv.m
src/pspm_extract_segments.m
src/pspm_find_valid_fixations.m

1. Fixes a bug in `pspm_extract_sessions` that only occurs under a specific option.
2. Fixes a bug in `pspm_find_valid_fixations` when gaze channel is in correct units
3. Fixes a bug in `pspm_dcm_inv` which could be handled by matlab until R2024a.
4. Fixes #685: a bug in help text of `pspm_convert_ecg2hb`

several bugfixes

---

src/pspm_display.m

Fixes #718 
The issue happened at line 32 in `pspm_display`. This is a line that is iteratively used when `pspm_display` is running. Initially, the `varargin` is set to be the input of `pspm_display`. In default, `varargin` is empty, so the line is not actually executed. In the next iteration, `varargin` becomes a multi-cell cell array, which is when `nargin` is no longer 0. This will not consider the situation that `pspm_display` actually has an input.
I am not fully clear what `gui_State.gui_Callback` is used for, since it is not really called much in this function. Therefore, I set a situation to identify whether it is processing the user's input as `varargin`, and this situation is determined in line 38 of the new version.
- This pull request updates the checking of input variable for …

Fix issue 718 -- `display`

---

src/pspm_data_editor.m

Fixes #717.
The issue was caused by the settings of UI component display. The settings of displaying `echo file` component and `output file` component are managed at lines 131 to 136 in `pspm_data_editor`. The lines functioned as following:
* If users call the GUI directly without specifying `options` in command, it will always display `echo file` and `output file`.
* If users call the GUI with specifying `options`, it will only display `output_file` when users have *not* specified `output_file`, and will only display `epoch_file` if users *have* specified `epoch_file`.
I am not fully clear why the logic was set to be like this. I think maybe we can discuss about how we want to set this. Currently I have disabled these customisations, so the two `epoch_file` and `output_file` modules will …

Fix issue 717 -- `data_editor`

---

src/pspm_trim.m

- `pspm_trim` fails when missing epochs are empty
- this is fixed now

fix edge case of empty epochs file in pspm_trim

---

src/pspm_display.m

- Fix an error in `pspm_display.m`
- `varargout` shall be preserved for outputs in some functions.
Other GUI functions (`pspm_display`, `pspm_data_editor`, `pspm_ecg_editor`) are also checked, and no similar issue has been detected.

Error correction in `pspm_display`

---

src/ext/matlabbatch/cfg_util.m

Fixes the "rev" issue when saving the current job (or job and script).
- Update cfg_util.m
- `rev` is no longer used by every function, but it may be available. The saving script would like to add the information, so there is a new checking condition added for the saving operation. The batch script can allow saving the current job without any issue now.

Fix rev issue

---

src/pspm_get_biosemi.m
src/pspm_get_biotrace.m
src/pspm_get_cnt.m
src/pspm_get_edf.m
src/pspm_get_vario.m
src/pspm_struct2vec.m

Fixes #727, an edge case reported in https://github.com/bachlab/PsPM/discussions/719.
- generalise syntax for `[S(:).field]` for cases in which `numel(S(i).field) ~= 1` in a new function `pspm_struct2vec`
- call this in several import functions
- fix a bug that leads to `markerinfos.values` being char rather than num.

fix edge case in marker value import

---

src/pspm_bf_lcrf_gm.m
src/pspm_bf_ldrf_gm.m
src/pspm_cfg/pspm_cfg_process_illuminance.m
src/pspm_cfg/pspm_cfg_run_proc_illuminance.m

- removes the response function options "duration" and "offset" from the illuminance GLM. There is no point changing these two if the other parameters cannot be changed.

fix illuminance GUI

---

src/pspm_check_model.m
src/pspm_dcm.m
src/pspm_extract_segments.m
src/pspm_glm.m
src/pspm_sf.m
src/pspm_sf_auc.m
src/pspm_sf_scl.m
src/pspm_tam.m

Fixes #816  .
- consider `timeunits == 'whole'` in `pspm_check_model` 
- fix some additional issues for methods SCL and AUC

fix SF issue with timeunits == 'whole'
