bachlab/PsPM

src/pspm_transfer_function.m

Changes asked by Dominik:
- Adding 3 more checkpoints in pspm_transfer_function.m which checks whenever c, Rs and offset are numeric or not.

TODO add checkpoints to pspm_transfer_function.m 

---

src/Import/viewpoint/import_viewpoint.m
src/pspm_get_viewpoint.m

Fixes #45 .
- Suppress all non-markers from the markers arrays in the `import_viewpoint` function.

Fixes issue #45: changes in import_viewpoint function

---

src/pspm_hb2hp.m
test/pspm_hb2hp_test.m

Fixes partially #37  .
- In `pspm_hb2hp.m`, I've modified a little bit warning messages.
- Created a test file for testing that function.
- It needs two files which I've attached here and which are supposed to go in the `ecg2hb`folder.
[test_data.zip](https://github.com/bachlab/PsPM/files/3762513/test_data.zip)

TODO: test for pspm_hb2hp.m

---

src/pspm_butter.m
test/pspm_butter_test.m

Fixes partially #37 .
- Modified a little bit warning messages.
- Created a test file for testing that function.

 TODO: test for pspm_butter.m 

---

src/pspm_filtfilt.m

Fixes #56  .
- Created a warning

Created a warning

---

src/pspm_filtfilt.m
test/pspm_filtfilt_test.m

Fixes partially #37 .
- Modified a little bit warning messages.
- Created a test file for testing that function (it needs the pull request #57 to work properly)

TODO: test for pspm_filtfilt.m

---

doc/PsPM_Manual.lyx
doc/release_notes.tex

Forgot to change release_notes.tex + typo

Forgot to change release_notes.tex

---

index.markdown
news.markdown

Changed release number + news

---

README.md

- Add badges that give info about latest release, latest website and its build status, and the license

Add badges with various info about repository

---

src/Import/eyelink/import_eyelink.m

Fixes #67 bis.
- Added a warning for markers with same timestamps

Added a warning for markers with same timestamps

---

src/pspm_bf_lcrf_gm.m
src/pspm_bf_ldrf_gm.m

Fixes #88  .
- Last line in both files changed, offset applied to the x coordinate.

Use bf_lcrf_gm and bf_ldrf_gm offset to shift the function

---

src/pspm_simple_qa.m

Correct minor error in comment in pspm_simple_qa

---

src/pspm_dcm.m
src/pspm_find_sounds.m
src/pspm_load_data.m

- Added warning to let users know a potential reason why no results are generated.
- Improved function menu into question dialog to set default values for a question dialog.
- Default fallback of overwriting dialog is set to 'Yes'

Fix issue 192

---

src/backroom/pspm_find_data_epochs.m
src/backroom/pspm_scr2ledalab.m
src/pspm_dcm.m
src/pspm_down.m
src/pspm_glm.m
src/pspm_load1.m
src/pspm_load_data.m
src/pspm_pfm.m
src/pspm_process_illuminance.m
src/pspm_sf.m
src/pspm_split_sessions.m

Fixes #196 .
- Make question dialog not shown in Jenkins (no window version)
- Change question dialogs from using function _menu_ to function _questdlg_

Fix issue 196

---

src/pspm_dcm.m

Fixes #185  .
- Change the method of converting cell array into matrix.

Fix Issue 185: based on the develop branch

---

src/pspm_cfg/pspm_cfg_resp_pp.m
src/pspm_cfg/pspm_cfg_run_split_sessions.m
src/pspm_cfg/pspm_cfg_split_sessions.m
src/pspm_split_sessions.m

Fixes #201 .
- Implement new split_sessions options.missing in GUI

Fix Issue 201

---

test/format_test_results.m
test/pspm_test.m
test/pspm_testcase.m

Fixes #232  .
- Fix a bug that may lead to the failure of generating test results.
- Fix a bug that may force users to manually build a new folder *ImportTestData*.

Fix issue 232

---

src/pspm_bf_data.m

Fixes #236 #231  .
- see title

New function template to allow users creating their own basis functions (bf) from a data vector

---

src/backroom/pspm_get_transfer_function.m

Update one of the convenience functions in "backroom" to work with current PsPM functions. This is not (yet) meant to be maintained for general use.

Update get_transfer_function for current PsP version

---

.gitignore
test/pspm_get_acq_test.m

- Update the test file for get_acq_test, since the test file name has been now anonymised.
- Update the encoding from MacOS Roman to UTF-8 and from CRLF (Windows) to LF (Unix)

Update test data for get_acq_test

---

src/pspm_dcm.m
src/pspm_interpolate.m

Fixes # 330.
- fix 2 edge cases in pspm_dcm (only one trial per session, or no trials in all sessions)
-  also fixes an edge case in pspm_interpolate (NaN at beginning or end of data)

DCM bugs with NaN

---

.github/workflows/main.yml

Fixes #340.
- Update to use test data from the private repository: [PsPM-data](https://github.com/bachlab/PsPM-data)

Fix issue 340 - test data remapping

---

src/pspm_rev_glm.m

Fixes #213 .
- `pspm_rev_glm`
- Convert to LF from CRLF
- In the matrix for displaying, normalise the values of each column (Line 69--73)
- Remove the warning of dominating data

Re-fix issue 213 - plot matrix

---

src/backroom/pspm_find_data_epochs.m
src/backroom/pspm_scr2ledalab.m
src/pspm_dcm.m
src/pspm_down.m
src/pspm_glm.m
src/pspm_init.m
src/pspm_load1.m
src/pspm_overwrite.m
src/pspm_pfm.m
src/pspm_process_illuminance.m
src/pspm_sf.m
test/pspm_load1_test.m
test/pspm_load_data_test.m
test/pspm_test.m
test/pspm_test_github_actions.m

Fixes #302.
- Update to provide an option of develop mode
- Add a new function `pspm_overwrite` to handle overwriting operations.
Please kindly keep this pull request open after approving it because I need to sort out some formatting issues and documents that I have not finished. Thanks.

Fix issue 302 - test mode for PsPM

---

src/pspm_convert_ppu2hb.m

Fixes #381.
- Update `pspm_convert_ppu2hb.m`
- Make the function stop if only one pulse is detected.

Fix issue 381 - pspm_convert_ppu2hb

---

src/pspm_options.m

Minor bug fix for `pspm_options`.
The issue was originally related to Marina's issue.
- `pspm_options`'s logic for `channel_action` has been improved.
- Some field names which contain `.` symbol have been modified to avoid reporting errors.

Bug fix for `pspm_options`

---

src/pspm_con2.m

Fixes #422.
- `pspm_con2`
- The action `overwrite` is now following `pspm_options`.

Fix issue 422 -- con2

---

src/pspm_dcm.m
src/pspm_dcm_inv.m

Fixes #458.
- `pspm_dcm`, `pspm_dcm_inv`
- Update incorrect `fixevents` assignment, from under `options` to under `model`.
- Update related help text.

Fix issue 458 -- dcm and dcm_inv

---

src/Import/eyelink/import_eyelink.m

Fixes #459 and #465.
- Update `import_eyelink`

Fix issues 459 and 465

---

src/pspm_glm.m

Fixes #467.
- Update the help text for `pspm_glm.m`.

Fix issue 467

---

doc/PsPM_release_checklist.md

Fixes #417
- future handling of develop and master branch documented in release notes

document master branch handling

---

src/pspm_split_sessions.m
test/pspm_split_sessions_test.m

Fixes #534 .
- Updated `split_sessions` as guided.
- Updated the test function for `split_sessions` where `missing_epoch` has been taken into consideration.

Fix issue 534 -- pspm_split_sessions

---

src/pspm_check_model.m
src/pspm_dcm.m

Fixes # 531.
- update help text for pspm_check_model and pspm_dcm

update help texts

---

src/pspm_extract_segments.m

Fixes #567 .
- fix only for DCM. Function should be refactored entirely in the future.

Use missing information for dcm in pspm_extract_segmenets

---

src/pspm_dcm.m

Fixes #565.
- initialise data matrix with NaN before inserting data of variable size.

fix issue 565

---

src/pspm_dcm.m

Fixes #571  .
- fix a bug in pspm_dcm that leads dropping sub-threshold missing data periods
- enable combining missing data epochs from file and data (as in a recent use case in CogLearn)

initial commit to fix #571

---

src/pspm_cfg/pspm_cfg_pp_emg.m
src/pspm_cfg/pspm_cfg_pp_emg_data.m
src/pspm_cfg/pspm_cfg_run_pp_emg_data.m
src/pspm_pp.m

Fixes #596.
- Update channel action issue in the GUI.
This pull request specifically fixes the bug of transferring the channel action value in the GUI when using EMG pre-processing. A systemic review of transferring such values can be found in #562.

Fix issue 596

---

src/pspm_leaky_integrator.m
src/pspm_pp.m

Fixes # 639.
- A new function pspm_leaky_integrator.
- Updated pspm_pp to make leaky_integrator accessible.

leaky integrator

---

src/pspm_leaky_integrator.m
src/pspm_pp.m

Fixes # 647.
- used snake case instead of camel case.
- Converted tau from seconds to samples using the sample rate in pspm_pp

Updated pspm_leaky_integrator and pspm_pp

---

src/pspm_pp.m

Fixes #680  .
- fix a wrong argument value in the call of `pspm_options` from `pspm_pp`

fix pspm_pp options call

---

courses.markdown

- changed course structure, as requested
- new embedded video links as replacing old ones (lectures 1, 3, 6, and tutorial 1)
- moved slides as requested 
- deleted the term "satellite" from the description of the last PsPM course
Still to be done: 
- upload new course slides 
- create download links for those new course slides

Changed course structure and replaced video links

---

courses.markdown

Fixes # .
- I replaced the linked image files with smaller preview versions for a better user experience.

Replaced video preview images with smaller versions.

---

src/pspm_pull_zenodo.m

Improves the helper function `pspm_pull_zenodo` to deal with a wider range of compression formats.

Improve pull zenodo

---

src/pspm_dcm.m
src/pspm_downsample.m
src/pspm_prepdata.m
test/pspm_downsample_test.m
test/pspm_prepdata_test.m

Fixes  #787 .
- pspm_downsample got the resample feature from (pspm_prepdata)
- pspm_prepdata uses  pspm_downsample
-  pspm_downsample uses pspm_dcm (implementation in progress).
- created pspm_downsample_test

787 pspm_downsample

---

src/pspm_get_smrx.m
src/pspm_import.m
src/pspm_load_data.m

Fixes #811 .
- fix a bug in smrx import when searching for channel
- fix a bug in smrx import that would turn all warnings off and not on again
- fix a bug in import that would prevent a file from being overwritten when the user is asked via dialogue

fix smrx and associated bugs
